/**
 * ExampleReview — a complete review generated by our AI Reviewer during a
 * real run, quoted verbatim from the supplementary material. The paper it
 * reviews is reproduced alongside the annotated manuscript.
 */
export default function ExampleReview() {
  return (
    <div className="example-review">
      <p className="review-note">
        The following content is an example review and annotated manuscript
        produced by our AI Reviewer and AppliedScientist for the paper
        mentioned below. Each critique is linked to the passage it refers to.
      </p>

      <p className="detail-kicker">
        Original manuscript
      </p>
      <p className="detail-note" style={{ marginTop: 0 }}>
        Gorka Abad, Stjepan Picek, Lorenzo Cavallaro, and Aitor Urbieta,{" "}
        <em>
          Context is the Key: Backdoor Attacks for In-Context Learning with
          Vision Transformers
        </em>{" "}
        (2026).
      </p>

      <blockquote className="review">
        <cite>Summary</cite>
        <p>
          This paper is an extended version of the authors&rsquo; earlier
          preprint on in-context backdoor attacks against masked-image-modeling
          vision transformers (Painter ViT-L and SegGPT ViT-L). The carried-over
          contributions are task-specific and task-agnostic data-poisoning
          backdoors. The genuinely new content is a measurement correction, a
          causal mechanism, and a defense: (1) the paper shows the standard
          degradation metric conflates the backdoor with the fact that the
          trigger occludes 10% of the input, since a clean model fed the trigger
          already loses 22&ndash;42% PSNR; it introduces trigger-controlled
          degradation and a targeted attack success rate (TASR) that remove this
          confounder, and re-measures the attack with them; (2) it attributes
          the attack to a &ldquo;context-routing hijack&rdquo; and demonstrates
          causality by projecting out an estimated trigger direction at
          inference; (3) it proposes context-consistency screening (CCS), a
          black-box detector that separates triggered from clean inputs (AUC
          1.00 on the test set). The attack and its cross-task transfer are
          reproduced on a second backbone (SegGPT).
        </p>
      </blockquote>

      <blockquote className="review">
        <cite>Strength &mdash; self-correction</cite>
        <p>
          The occlusion-confounder analysis is the strongest part. The exact
          within-construction decomposition &mdash; clean/triggered =
          22.76&rarr;15.84, compromised/triggered = 5.37, giving 76.4% total =
          30.4% occlusion + 46.0% backdoor &mdash; is clearly stated and
          arithmetically consistent. The paper explicitly corrects its own
          earlier evaluation (&ldquo;our earlier evaluation understated
          cross-task transfer because its metric could not see it&rdquo;),
          which is rare and commendable.
        </p>
      </blockquote>

      <blockquote className="review">
        <cite>Weakness &mdash; detection results are a 15-query result</cite>
        <p>
          CCS, STRIP, activation clustering, and spectral signatures all report
          AUC/accuracy 1.00 on the compromised model, but on only 15 held-out
          LoL test queries. An AUC computed over ordered pairs of 15 queries
          cannot distinguish 1.00 from, say, 0.99, and the defense section is
          where the weakest statistics support the strongest-sounding numbers.
          CCS is also only validated on LoL, not on the native task suite or on
          SegGPT.
        </p>
      </blockquote>

      <blockquote className="review">
        <cite>Suggestion, tied to the weakness above</cite>
        <p>
          Run TASR on the native pipelines (SRD, SIDD, ADE20K, NYUv2, FSS-1000)
          for the LoL-poisoned model. This is the single experiment that would
          convert the cross-task transfer claim from &ldquo;demonstrated in a
          controlled construction&rdquo; to &ldquo;demonstrated in the
          paper&rsquo;s own primary evaluation protocol.&rdquo; Report TASR and
          trigger-controlled degradation alongside the existing degradation
          values for the same native test sets so the two views are directly
          comparable.
        </p>
      </blockquote>

      <blockquote className="review">
        <cite>Scores</cite>
        <p>
          <strong>Soundness</strong> 3/4 &mdash; The confounder analysis,
          decomposition, causal intervention, and specificity controls are
          exemplary; the cross-task-transfer and detection claims rest on
          nonstandard or tiny test constructions. <strong>Presentation</strong>{" "}
          3/4 &mdash; Dense but clear, and unusually honest about limitations;
          marred by a handful of small numerical inconsistencies across
          sections. <strong>Contribution</strong> 3/4 &mdash; The attack itself
          is prior work, but the measurement correction, the context-routing
          mechanism, and the black-box defense are meaningful, citable additions
          that improve the whole sub-field&rsquo;s evaluation practice.{" "}
          <strong>Overall</strong> 6/10. <strong>Confidence</strong> 4/5.{" "}
          <strong>Decision</strong>: Accept.
        </p>
      </blockquote>

      <div className="review-source">
        <div>
          <span className="label">Annotated manuscript</span>
          <p>
            <a href="/exhibits/idea09_full_annotated.pdf">
              Review linked to the passages it refers to (PDF)
            </a>
          </p>
        </div>
        <div>
          <span className="label">Original submission</span>
          <p>
            <a href="/exhibits/idea09_original_score4.pdf">
              Score 4, before revision (PDF)
            </a>
          </p>
        </div>
        <div>
          <span className="label">Revised manuscript</span>
          <p>
            <a href="/exhibits/idea09_revised.pdf">
              Manuscript after revision (PDF)
            </a>
          </p>
        </div>
      </div>
    </div>
  );
}
